//total count actions
export const CLEAR_COUNTER = "CLEAR_COUNTER";
export const INCREMENT_ONE = "INCREMENT_ONE";
export const INCREMENT_SIX = "INCREMENT_SIX";
export const INCREMENT_TWELVE = "INCREMENT_TWELVE";

//individual donut counter actions
export const INCREMENT_SUGAR_GLAZED = "INCREMENT_SUGAR_GLAZED";
export const DECREMENT_SUGAR_GLAZED = "DECREMENT_SUGAR_GLAZED";
export const INCREMENT_CHOCOLATE = "INCREMENT_CHOCOLATE";
export const DECREMENT_CHOCOLATE = "DECREMENT_CHOCOLATE";
export const INCREMENT_BLUEBERRY = "INCREMENT_BLUEBERRY";
export const DECREMENT_BLUEBERRY = "DECREMENT_BLUEBERRY";
export const INCREMENT_STRAWBERRY = "INCREMENT_STRAWBERRY";
export const DECREMENT_STRAWBERRY = "DECREMENT_STRAWBERRY";
export const INCREMENT_CONFETTI = "INCREMENT_CONFETTI";
export const DECREMENT_CONFETTI = "DECREMENT_CONFETTI";

//customer data actions
export const SELECTED_CUSTOMER = "SELECTED_CUSTOMER";
